FROM node:14.14.0-alpine3.12 as app

WORKDIR /src

# Enviroment
ENV SHOP=shoppingproductsrus.myshopify.com
ENV SCOPES=write_products,write_customers,write_draft_orders,write_script_tags,read_script_tags
ENV TYPEORM_HOST=ls-65f3464dc451ce359854f23226ce6946f9021c0d.cjynhwfinaps.us-east-2.rds.amazonaws.com
ENV TYPEORM_USER=dbmasteruser
ENV TYPEORM_PASSWORD="es),<%<Oy*nPtx3K.D}F|Y%=f6=[E=Z-"
ENV SHOPIFY_API_KEY=38b443ca48b137615d92fa5b6db4633f
ENV SHOPIFY_API_SECRET=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
ENV HOST=https://production.accessorybar.jttech.dev
ENV TYPEORM_DATABASE=production
ENV SHOPFRONT_SCRIPT_SRC=https://cdn.shopify.com/s/files/1/0425/8273/7063/files/index.min_c9dd5f8b-221c-40e2-9521-0a631258f709.js?v=1603916629

# Install 
COPY package.json package.json
RUN npm install

# RUN
COPY . .
RUN npm run build
EXPOSE 8081 5432
CMD [ "npm", "run", "start" ]

