FROM node:14.14.0-alpine3.12 as app

WORKDIR /src

# Enviroment
ENV SHOP=shoppingproductsrus.myshopify.com
ENV SCOPES=read_products,write_script_tags,read_script_tags
ENV TYPEORM_HOST=ls-cf2c99af9c14c9362a9ef3c25ed8575a9f53e78c.cjynhwfinaps.us-east-2.rds.amazonaws.com
ENV TYPEORM_USER=dbmasteruser
ENV TYPEORM_PASSWORD=^97)lUpysjse*A}c}:lc}$,0cl&8s4g<
ENV SHOPIFY_API_KEY=9660ecc408a6a27343dd5357cc3b197c
ENV SHOPIFY_API_SECRET=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
ENV HOST=https://staging.accessorybar.jttech.dev
ENV TYPEORM_DATABASE=staging_db
ENV SHOPFRONT_SCRIPT_SRC=https://cdn.shopify.com/s/files/1/0425/8273/7063/files/index.min_dd102897-9e7d-44a2-9736-51a34ba942fe.js?v=1608155334

# Install 
COPY package.json package.json
RUN npm install

# RUN
COPY . .
RUN npm run build
EXPOSE 8081 5432
CMD [ "npm", "run", "start" ]

