FROM node:14.14.0-alpine3.12 as app

WORKDIR /src

# Enviroment
ENV SHOP=shoppingproductsrus.myshopify.com
ENV SCOPES=read_products,write_script_tags,read_script_tags
ENV TYPEORM_HOST=ls-cf2c99af9c14c9362a9ef3c25ed8575a9f53e78c.cjynhwfinaps.us-east-2.rds.amazonaws.com
ENV TYPEORM_USER=dbmasteruser
ENV TYPEORM_PASSWORD=^97)lUpysjse*A}c}:lc}$,0cl&8s4g<
ENV SHOPIFY_API_KEY=38b443ca48b137615d92fa5b6db4633f
ENV SHOPIFY_API_SECRET=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
ENV HOST=https://production.accessorybar.jttech.dev
ENV TYPEORM_DATABASE=production_db
ENV SHOPFRONT_SCRIPT_SRC=https://cdn.shopify.com/s/files/1/0425/8273/7063/files/index.min_5bf40a65-75cb-44b1-9077-a0c8c116663d.js?v=1608155366

# Install 
COPY package.json package.json
RUN npm install

# RUN
COPY . .
RUN npm run build
EXPOSE 8081 5432
CMD [ "npm", "run", "start" ]

