name: Deploy to Production

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build and Push Docker Image to Github Packages
    needs:
      - test
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Push to github packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jackjttech/accessory_bar/production
          dockerfile: ./Dockerfile-Production
          tag_with_ref: true

  deploy:
    runs-on: ubuntu-20.04
    name: Deploy to production
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PRODUCTION_KNOWN_HOSTS }}
      - name: Sync docker compose file
        run: rsync ./docker-compose-production.yml ubuntu@3.12.97.245:/home/ubuntu
      - name: Remove compose file
        run: ssh -t ubuntu@3.12.97.245 sudo rm -f docker-compose.yml
      - name: Rename compose file
        run: ssh -t ubuntu@3.12.97.245 sudo mv docker-compose-production.yml docker-compose.yml
      - name: Sync nginx default conf
        run: rsync nginx/production/default.conf ubuntu@3.12.97.245:/home/ubuntu/nginx/default.conf
      - name: Log into docker
        run: ssh -t ubuntu@3.12.97.245 sudo docker login https://docker.pkg.github.com -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest docker images
        run: ssh -t ubuntu@3.12.97.245 sudo docker-compose pull
      - name: Docker down anything already running
        run: ssh -t ubuntu@3.12.97.245 sudo docker-compose down -v
      - name: Docker up
        run: ssh -t ubuntu@3.12.97.245 sudo docker-compose up -d
      - name: Docker check
        run: ssh -t ubuntu@3.12.97.245 sudo docker-compose ps
